#!/usr/bin/env python3
"""Generate Custom GPT Knowledge and platform release ZIP files."""

from __future__ import annotations

import zipfile
from pathlib import Path


VERSION = "1.0.0"
ROOT = Path(__file__).resolve().parents[1]
SKILL = ROOT / "packages" / "sam-aobpg"
CUSTOM_GPT = ROOT / "adapters" / "custom-gpt"
RELEASES = ROOT / "releases"


def write_knowledge() -> Path:
    destination = CUSTOM_GPT / "knowledge" / "sam-knowledge.md"
    sections = [
        "# SAM Core Knowledge\n\nGenerated from the canonical SAM Agent Skill references. Do not edit this file directly.\n"
    ]
    for source in sorted((SKILL / "references").glob("*.md")):
        sections.append(f"\n---\n\n<!-- source: {source.name} -->\n\n{source.read_text(encoding='utf-8').strip()}\n")
    destination.write_text("".join(sections), encoding="utf-8", newline="\n")
    return destination


def add_tree(archive: zipfile.ZipFile, source: Path, prefix: str, exclude: set[str] | None = None) -> None:
    exclude = exclude or set()
    for path in sorted(source.rglob("*")):
        if path.is_dir():
            continue
        relative = path.relative_to(source)
        if relative.parts and relative.parts[0] in exclude:
            continue
        archive.write(path, Path(prefix) / relative)


def build_zip(name: str, source: Path, prefix: str, exclude: set[str] | None = None) -> Path:
    destination = RELEASES / name
    with zipfile.ZipFile(destination, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        add_tree(archive, source, prefix, exclude)
    return destination


def build_template_zip(name: str, source: Path, prefix: str) -> Path:
    destination = RELEASES / name
    with zipfile.ZipFile(destination, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        add_tree(archive, source, prefix)
    return destination


def main() -> None:
    RELEASES.mkdir(parents=True, exist_ok=True)
    skill_schemas = SKILL / "schemas"
    skill_schemas.mkdir(parents=True, exist_ok=True)
    for schema in sorted((ROOT / "schemas").glob("*.json")):
        (skill_schemas / schema.name).write_text(schema.read_text(encoding="utf-8"), encoding="utf-8", newline="\n")
    write_knowledge()
    build_zip(f"sam-openai-skill-v{VERSION}.zip", SKILL, "sam-aobpg")
    build_zip(f"sam-claude-skill-v{VERSION}.zip", SKILL, "sam-aobpg", {"agents"})
    build_template_zip(f"sam-custom-gpt-v{VERSION}.zip", CUSTOM_GPT, "sam-custom-gpt")
    build_template_zip(
        f"sam-brand-pack-template-v{VERSION}.zip",
        SKILL / "assets" / "templates" / "brand-pack",
        "sam-brand-pack-template",
    )
    build_template_zip(
        f"sam-example-campaign-v{VERSION}.zip",
        ROOT / "examples" / "campaigns" / "sunny-spoon-back-to-school",
        "sunny-spoon-back-to-school",
    )
    print(f"Built releases in {RELEASES}")


if __name__ == "__main__":
    main()
